version: "3"
services:

  frontend:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./certificates/letsencrypt:/etc/letsencrypt
      - ./certificates/certbot:/var/www/certbot
